import http from "node:http";
import {createHash} from "node:crypto";
const COLLECTOR_ID="FPSP3-GATE-D1-W1-BTC-ETH-1.0",ALLOWED_SYMBOLS=Object.freeze(["BTC_USDT","ETH_USDT"]),T0="2026-09-30T00:00:00.000Z",SOURCE="GATE_PUBLIC_API_V4_FUTURES_USDT_CANDLESTICKS";
const hash=v=>createHash("sha256").update(typeof v==="string"?v:canonical(v)).digest("hex"),canonical=v=>JSON.stringify(v,Object.keys(v??{}).sort());
function assertConfig(s){if(!Array.isArray(s)||JSON.stringify(s)!==JSON.stringify(ALLOWED_SYMBOLS))throw Error("BTC_ETH_ONLY_ALLOWLIST_REQUIRED")}
function gateUrl(s){assertConfig(ALLOWED_SYMBOLS);if(!ALLOWED_SYMBOLS.includes(s))throw Error("SYMBOL_REJECTED_BEFORE_NETWORK");return `https://api.gateio.ws/api/v4/futures/usdt/candlesticks?contract=${s}&interval=1d&limit=10`}
function envelope(symbol,row,observedAt,startedAt){if(!ALLOWED_SYMBOLS.includes(symbol)||!row||typeof row!=="object")throw Error("INVALID_CANDLE");const at=(i,k)=>Array.isArray(row)?row[i]:row[k],startMs=Number(at(0,"t"))*1000,availableAt=new Date(startMs+86400000).toISOString();if(!Number.isFinite(startMs))throw Error("INVALID_CANDLE_TIME");if(Date.parse(availableAt)>Date.parse(observedAt))return null;const normalized={symbol,timeframe:"1D",eventTime:new Date(startMs).toISOString(),open:String(at(6,"o")),high:String(at(3,"h")),low:String(at(4,"l")),close:String(at(2,"c")),volume:String(at(1,"v"))},rawHash=hash(JSON.stringify(row)),normalizedHash=hash(canonical(normalized)),provenance=Date.parse(availableAt)<Date.parse(T0)||Date.parse(availableAt)<Date.parse(startedAt)?"WARMUP_ONLY":"LIVE_OBSERVED",core={sealHash:"633e42d5571c2bc17bc119d8c10fa7ac3446e05ade5800688aa26f39b5cc5392",symbol,timeframe:"1D",eventTime:normalized.eventTime,firstObservedAt:observedAt,availableAt,provenance,sourceIdentity:SOURCE,rawHash,normalizedHash,parentHashes:[],normalizedBar:normalized};return {...core,evidenceHash:hash(canonical(core))}}
const port=Number(process.env.PORT||3000),vaultUrl=process.env.VAULT_URL,auth=process.env.SITES_AUTHORIZATION;if(!vaultUrl||!auth)throw Error("VAULT_URL_AND_SITES_AUTHORIZATION_REQUIRED");if(process.env.SYMBOLS&&process.env.SYMBOLS!==ALLOWED_SYMBOLS.join(","))throw Error("SYMBOL_CONFIG_REJECTED_BEFORE_NETWORK");
const startedAt=new Date().toISOString();let state="STARTING",lastPollAt=null,lastSuccessAt=null,lastError=null,gateReads={BTC_USDT:0,ETH_USDT:0},solReads=0,accepted=0,warmup=0;const headers={"content-type":"application/json","OAI-Sites-Authorization":`Bearer ${auth}`};
async function vault(body){const r=await fetch(vaultUrl,{method:"POST",headers,body:JSON.stringify({collectorId:COLLECTOR_ID,allowedSymbols:ALLOWED_SYMBOLS,...body})}),v=await r.json();if(!r.ok)throw Error(`VAULT_${r.status}:${v.error??"ERROR"}`);return v}
async function poll(){lastPollAt=new Date().toISOString();try{for(const symbol of ALLOWED_SYMBOLS){const r=await fetch(gateUrl(symbol),{headers:{accept:"application/json"}});gateReads[symbol]++;if(!r.ok)throw Error(`GATE_${symbol}_${r.status}`);const rows=await r.json(),observedAt=new Date().toISOString();for(const row of rows){const item=envelope(symbol,row,observedAt,startedAt);if(!item)continue;await vault({action:"APPEND_EVIDENCE",...item});item.provenance==="LIVE_OBSERVED"?accepted++:warmup++}}lastSuccessAt=new Date().toISOString();lastError=null;state="COLLECTING_BLIND"}catch(e){lastError=String(e?.message??e);state="FAIL_CLOSED"}}
const server=http.createServer((q,s)=>{if(q.url!=="/health"&&q.url!=="/status"){s.writeHead(404).end();return}s.setHeader("content-type","application/json");s.end(JSON.stringify({service:"fpsp3-future-evidence-collector",collectorId:COLLECTOR_ID,state,startedAt,lastPollAt,lastSuccessAt,lastError,allowedSymbols:ALLOWED_SYMBOLS,gateReads,solReads,accepted,warmup,authenticatedGateCalls:0,tradingWrites:0,performanceEndpoints:0}))});
server.listen(port,async()=>{try{await vault({action:"PERSIST_SEAL"});state="COLLECTING_BLIND";await poll();setInterval(poll,60000).unref()}catch(e){lastError=String(e?.message??e);state="FAIL_CLOSED"}});
